version: '3.1'

services:
  auth_server:
    container_name: 'auth_server'
    ports:
      - 3000:3000
    build: ./server/
    # links:
    #    - mongoservice
    restart: on-failure

  mongoservice:
    image: mongo:latest
    container_name: "mongoservice"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
     - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod
    restart: on-failure

  nginx:
    image: nginx: latest
    container_name: nginx
    restart: on-failure
    ports:
      - 8081:80
    volumes:
      - ./client/dist:/usr/share/nginx/html
